# Generated by Django 5.1.6 on 2025-02-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_first_name_alter_member_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
